import { TestDefinition, Athlete } from './types';

export const TEST_DEFINITIONS: TestDefinition[] = [
  {
    id: 'height',
    name: 'قد',
    unit: 'سانتی‌متر',
    description: 'قد ایستاده',
    category: 'body',
    standards: [],
  },
  {
    id: 'weight',
    name: 'وزن',
    unit: 'کیلوگرم',
    description: 'وزن بدن',
    category: 'body',
    standards: [],
  },
  {
    id: 'bmi',
    name: 'BMI',
    unit: 'kg/m²',
    description: 'شاخص توده بدنی (محاسبه خودکار)',
    category: 'body',
    isComputed: true,
    computeFrom: ['height', 'weight'],
    standards: [
      {
        gender: 'both', ageMin: 10, ageMax: 99,
        excellent: { min: 18.5, max: 24.9 },
        good: { min: 17.0, max: 26.9 },
        average: { min: 15.0, max: 29.9 },
        poor: { min: 0, max: 99 },
      },
    ],
  },
  {
    id: 'body_fat',
    name: 'درصد چربی',
    unit: 'درصد',
    description: 'درصد چربی بدن',
    category: 'body',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 17,
        excellent: { min: 10, max: 18 },
        good: { min: 18, max: 22 },
        average: { min: 22, max: 27 },
        poor: { min: 27, max: 50 },
      },
      {
        gender: 'male', ageMin: 18, ageMax: 99,
        excellent: { min: 8, max: 15 },
        good: { min: 15, max: 20 },
        average: { min: 20, max: 25 },
        poor: { min: 25, max: 50 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 17,
        excellent: { min: 15, max: 22 },
        good: { min: 22, max: 27 },
        average: { min: 27, max: 32 },
        poor: { min: 32, max: 60 },
      },
      {
        gender: 'female', ageMin: 18, ageMax: 99,
        excellent: { min: 15, max: 22 },
        good: { min: 22, max: 28 },
        average: { min: 28, max: 35 },
        poor: { min: 35, max: 60 },
      },
    ],
  },
  {
    id: 'vertical_jump',
    name: 'پرش عمودی',
    unit: 'سانتی‌متر',
    description: 'ارتفاع پرش عمودی (بیشتر بهتر)',
    category: 'power',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 12,
        excellent: { min: 40, max: 999 },
        good: { min: 30, max: 40 },
        average: { min: 20, max: 30 },
        poor: { min: 0, max: 20 },
      },
      {
        gender: 'male', ageMin: 13, ageMax: 15,
        excellent: { min: 45, max: 999 },
        good: { min: 35, max: 45 },
        average: { min: 25, max: 35 },
        poor: { min: 0, max: 25 },
      },
      {
        gender: 'male', ageMin: 16, ageMax: 18,
        excellent: { min: 55, max: 999 },
        good: { min: 40, max: 55 },
        average: { min: 30, max: 40 },
        poor: { min: 0, max: 30 },
      },
      {
        gender: 'male', ageMin: 19, ageMax: 99,
        excellent: { min: 60, max: 999 },
        good: { min: 45, max: 60 },
        average: { min: 35, max: 45 },
        poor: { min: 0, max: 35 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 12,
        excellent: { min: 35, max: 999 },
        good: { min: 25, max: 35 },
        average: { min: 15, max: 25 },
        poor: { min: 0, max: 15 },
      },
      {
        gender: 'female', ageMin: 13, ageMax: 99,
        excellent: { min: 40, max: 999 },
        good: { min: 30, max: 40 },
        average: { min: 20, max: 30 },
        poor: { min: 0, max: 20 },
      },
    ],
  },
  {
    id: 'agility',
    name: 'چابکی (ایلینویز)',
    unit: 'ثانیه',
    description: 'آزمون چابکی ایلینویز — زمان کمتر بهتر است',
    category: 'speed',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 12,
        excellent: { min: 0, max: 15.9 },
        good: { min: 15.9, max: 17.0 },
        average: { min: 17.0, max: 18.5 },
        poor: { min: 18.5, max: 99 },
      },
      {
        gender: 'male', ageMin: 13, ageMax: 99,
        excellent: { min: 0, max: 15.2 },
        good: { min: 15.2, max: 16.1 },
        average: { min: 16.1, max: 18.2 },
        poor: { min: 18.2, max: 99 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 12,
        excellent: { min: 0, max: 17.0 },
        good: { min: 17.0, max: 18.5 },
        average: { min: 18.5, max: 20.0 },
        poor: { min: 20.0, max: 99 },
      },
      {
        gender: 'female', ageMin: 13, ageMax: 99,
        excellent: { min: 0, max: 17.0 },
        good: { min: 17.0, max: 18.0 },
        average: { min: 18.0, max: 19.5 },
        poor: { min: 19.5, max: 99 },
      },
    ],
  },
  {
    id: 'balance',
    name: 'تعادل (یک پا)',
    unit: 'ثانیه',
    description: 'ایستادن روی یک پا با چشمان بسته (بیشتر بهتر)',
    category: 'balance',
    standards: [
      {
        gender: 'both', ageMin: 10, ageMax: 14,
        excellent: { min: 20, max: 999 },
        good: { min: 10, max: 20 },
        average: { min: 5, max: 10 },
        poor: { min: 0, max: 5 },
      },
      {
        gender: 'both', ageMin: 15, ageMax: 99,
        excellent: { min: 25, max: 999 },
        good: { min: 15, max: 25 },
        average: { min: 8, max: 15 },
        poor: { min: 0, max: 8 },
      },
    ],
  },
  {
    id: 'flexibility',
    name: 'انعطاف (نشست و برخاست)',
    unit: 'سانتی‌متر',
    description: 'آزمون نشست و رسیدن (بیشتر بهتر)',
    category: 'flexibility',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 14,
        excellent: { min: 15, max: 99 },
        good: { min: 8, max: 15 },
        average: { min: 0, max: 8 },
        poor: { min: -50, max: 0 },
      },
      {
        gender: 'male', ageMin: 15, ageMax: 99,
        excellent: { min: 20, max: 99 },
        good: { min: 10, max: 20 },
        average: { min: 2, max: 10 },
        poor: { min: -50, max: 2 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 14,
        excellent: { min: 20, max: 99 },
        good: { min: 12, max: 20 },
        average: { min: 5, max: 12 },
        poor: { min: -50, max: 5 },
      },
      {
        gender: 'female', ageMin: 15, ageMax: 99,
        excellent: { min: 25, max: 99 },
        good: { min: 16, max: 25 },
        average: { min: 8, max: 16 },
        poor: { min: -50, max: 8 },
      },
    ],
  },
  {
    id: 'grip_strength',
    name: 'قدرت دست',
    unit: 'کیلوگرم',
    description: 'قدرت گرفتن دست با دینامومتر (بیشتر بهتر)',
    category: 'power',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 12,
        excellent: { min: 25, max: 99 },
        good: { min: 18, max: 25 },
        average: { min: 12, max: 18 },
        poor: { min: 0, max: 12 },
      },
      {
        gender: 'male', ageMin: 13, ageMax: 17,
        excellent: { min: 40, max: 99 },
        good: { min: 30, max: 40 },
        average: { min: 20, max: 30 },
        poor: { min: 0, max: 20 },
      },
      {
        gender: 'male', ageMin: 18, ageMax: 99,
        excellent: { min: 55, max: 99 },
        good: { min: 40, max: 55 },
        average: { min: 30, max: 40 },
        poor: { min: 0, max: 30 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 12,
        excellent: { min: 20, max: 99 },
        good: { min: 15, max: 20 },
        average: { min: 10, max: 15 },
        poor: { min: 0, max: 10 },
      },
      {
        gender: 'female', ageMin: 13, ageMax: 99,
        excellent: { min: 32, max: 99 },
        good: { min: 22, max: 32 },
        average: { min: 15, max: 22 },
        poor: { min: 0, max: 15 },
      },
    ],
  },
  {
    id: 'speed',
    name: 'سرعت (۴۰ متر)',
    unit: 'ثانیه',
    description: 'دو ۴۰ متر سرعت — زمان کمتر بهتر است',
    category: 'speed',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 12,
        excellent: { min: 0, max: 5.5 },
        good: { min: 5.5, max: 6.2 },
        average: { min: 6.2, max: 7.0 },
        poor: { min: 7.0, max: 99 },
      },
      {
        gender: 'male', ageMin: 13, ageMax: 17,
        excellent: { min: 0, max: 5.0 },
        good: { min: 5.0, max: 5.6 },
        average: { min: 5.6, max: 6.3 },
        poor: { min: 6.3, max: 99 },
      },
      {
        gender: 'male', ageMin: 18, ageMax: 99,
        excellent: { min: 0, max: 4.8 },
        good: { min: 4.8, max: 5.4 },
        average: { min: 5.4, max: 6.0 },
        poor: { min: 6.0, max: 99 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 12,
        excellent: { min: 0, max: 6.0 },
        good: { min: 6.0, max: 6.8 },
        average: { min: 6.8, max: 7.5 },
        poor: { min: 7.5, max: 99 },
      },
      {
        gender: 'female', ageMin: 13, ageMax: 99,
        excellent: { min: 0, max: 5.5 },
        good: { min: 5.5, max: 6.2 },
        average: { min: 6.2, max: 7.0 },
        poor: { min: 7.0, max: 99 },
      },
    ],
  },
  {
    id: 'endurance',
    name: 'استقامت (کوپر)',
    unit: 'متر',
    description: 'دو ۱۲ دقیقه‌ای کوپر — مسافت بیشتر بهتر است',
    category: 'endurance',
    standards: [
      {
        gender: 'male', ageMin: 10, ageMax: 12,
        excellent: { min: 2300, max: 9999 },
        good: { min: 1900, max: 2300 },
        average: { min: 1500, max: 1900 },
        poor: { min: 0, max: 1500 },
      },
      {
        gender: 'male', ageMin: 13, ageMax: 17,
        excellent: { min: 2700, max: 9999 },
        good: { min: 2200, max: 2700 },
        average: { min: 1800, max: 2200 },
        poor: { min: 0, max: 1800 },
      },
      {
        gender: 'male', ageMin: 18, ageMax: 99,
        excellent: { min: 3100, max: 9999 },
        good: { min: 2600, max: 3100 },
        average: { min: 2100, max: 2600 },
        poor: { min: 0, max: 2100 },
      },
      {
        gender: 'female', ageMin: 10, ageMax: 12,
        excellent: { min: 2000, max: 9999 },
        good: { min: 1600, max: 2000 },
        average: { min: 1200, max: 1600 },
        poor: { min: 0, max: 1200 },
      },
      {
        gender: 'female', ageMin: 13, ageMax: 99,
        excellent: { min: 2300, max: 9999 },
        good: { min: 1900, max: 2300 },
        average: { min: 1500, max: 1900 },
        poor: { min: 0, max: 1500 },
      },
    ],
  },
];

export const SPORTS = [
  'فوتبال', 'فوتسال', 'بسکتبال', 'والیبال', 'شنا', 'دو و میدانی',
  'ژیمناستیک', 'کشتی', 'جودو', 'کاراته', 'تکواندو', 'بدمینتون',
  'تنیس', 'هندبال', 'بوکس', 'دوچرخه‌سواری', 'وزنه‌برداری', 'سایر',
];

export const SPORT_LEVEL_LABELS: Record<string, string> = {
  beginner: 'مبتدی',
  intermediate: 'متوسط',
  advanced: 'پیشرفته',
  professional: 'حرفه‌ای',
};

const now = new Date();
const dateStr = (y: number, m: number, d: number) =>
  `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`;

export const INITIAL_ATHLETES: Athlete[] = [
  {
    id: 'a1',
    firstName: 'علی',
    lastName: 'احمدی',
    mobile: '09121234567',
    birthDate: '2009-04-15',
    gender: 'male',
    sport: 'فوتبال',
    sportLevel: 'intermediate',
    injuryHistory: 'پیچ‌خوردگی مچ پا در سال ۱۴۰۳',
    notes: 'بازیکن خط میانی تیم مدرسه',
    createdAt: dateStr(now.getFullYear(), 1, 10),
    sessions: [
      {
        id: 's1a1',
        date: dateStr(now.getFullYear(), 3, 5),
        label: 'ارزیابی اول — خرداد',
        notes: 'ارزیابی ابتدایی فصل',
        results: [
          { testId: 'height', value: 162 },
          { testId: 'weight', value: 55 },
          { testId: 'bmi', value: 20.9 },
          { testId: 'body_fat', value: 16 },
          { testId: 'vertical_jump', value: 38 },
          { testId: 'agility', value: 15.8 },
          { testId: 'balance', value: 18 },
          { testId: 'flexibility', value: 12 },
          { testId: 'grip_strength', value: 35 },
          { testId: 'speed', value: 5.4 },
          { testId: 'endurance', value: 2400 },
        ],
      },
      {
        id: 's2a1',
        date: dateStr(now.getFullYear(), 6, 10),
        label: 'ارزیابی دوم — شهریور',
        notes: 'بعد از ۳ ماه تمرین منظم',
        results: [
          { testId: 'height', value: 163 },
          { testId: 'weight', value: 54 },
          { testId: 'bmi', value: 20.3 },
          { testId: 'body_fat', value: 14 },
          { testId: 'vertical_jump', value: 44 },
          { testId: 'agility', value: 15.2 },
          { testId: 'balance', value: 22 },
          { testId: 'flexibility', value: 15 },
          { testId: 'grip_strength', value: 38 },
          { testId: 'speed', value: 5.1 },
          { testId: 'endurance', value: 2650 },
        ],
      },
    ],
  },
  {
    id: 'a2',
    firstName: 'زهرا',
    lastName: 'کریمی',
    mobile: '09357654321',
    birthDate: '2007-08-22',
    gender: 'female',
    sport: 'والیبال',
    sportLevel: 'advanced',
    injuryHistory: 'بدون سابقه آسیب',
    notes: 'عضو تیم استانی نوجوانان',
    createdAt: dateStr(now.getFullYear(), 2, 1),
    sessions: [
      {
        id: 's1a2',
        date: dateStr(now.getFullYear(), 2, 20),
        label: 'ارزیابی اول — اردیبهشت',
        notes: '',
        results: [
          { testId: 'height', value: 172 },
          { testId: 'weight', value: 62 },
          { testId: 'bmi', value: 21.0 },
          { testId: 'body_fat', value: 20 },
          { testId: 'vertical_jump', value: 43 },
          { testId: 'agility', value: 16.8 },
          { testId: 'balance', value: 28 },
          { testId: 'flexibility', value: 24 },
          { testId: 'grip_strength', value: 30 },
          { testId: 'speed', value: 5.9 },
          { testId: 'endurance', value: 2100 },
        ],
      },
    ],
  },
  {
    id: 'a3',
    firstName: 'محمد',
    lastName: 'رضایی',
    mobile: '09019876543',
    birthDate: '2001-12-05',
    gender: 'male',
    sport: 'بسکتبال',
    sportLevel: 'professional',
    injuryHistory: 'شکستگی ترقوه در سال ۱۴۰۱ — بهبود کامل',
    notes: 'عضو تیم ملی جوانان',
    createdAt: dateStr(now.getFullYear() - 1, 11, 15),
    sessions: [
      {
        id: 's1a3',
        date: dateStr(now.getFullYear(), 1, 15),
        label: 'ارزیابی اول — بهمن',
        notes: 'آمادگی برای فصل جدید',
        results: [
          { testId: 'height', value: 195 },
          { testId: 'weight', value: 88 },
          { testId: 'bmi', value: 23.1 },
          { testId: 'body_fat', value: 11 },
          { testId: 'vertical_jump', value: 68 },
          { testId: 'agility', value: 14.9 },
          { testId: 'balance', value: 30 },
          { testId: 'flexibility', value: 22 },
          { testId: 'grip_strength', value: 62 },
          { testId: 'speed', value: 4.6 },
          { testId: 'endurance', value: 3200 },
        ],
      },
    ],
  },
  {
    id: 'a4',
    firstName: 'نگین',
    lastName: 'صادقی',
    mobile: '09154321987',
    birthDate: '2011-03-18',
    gender: 'female',
    sport: 'شنا',
    sportLevel: 'intermediate',
    injuryHistory: '',
    notes: 'دارای مدال منطقه‌ای در شنای پروانه',
    createdAt: dateStr(now.getFullYear(), 3, 1),
    sessions: [
      {
        id: 's1a4',
        date: dateStr(now.getFullYear(), 3, 20),
        label: 'ارزیابی اول — فروردین',
        notes: '',
        results: [
          { testId: 'height', value: 148 },
          { testId: 'weight', value: 40 },
          { testId: 'bmi', value: 18.3 },
          { testId: 'body_fat', value: 17 },
          { testId: 'vertical_jump', value: 28 },
          { testId: 'agility', value: 17.5 },
          { testId: 'balance', value: 15 },
          { testId: 'flexibility', value: 26 },
          { testId: 'grip_strength', value: 18 },
          { testId: 'speed', value: 6.5 },
          { testId: 'endurance', value: 1700 },
        ],
      },
    ],
  },
];
